version: "3"

services:
  gympass:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gympass
